[package]
name = "axer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-multipart = "0.7.2"
actix-web = "4.8.0"
env_logger = "0.11.5"
log = "0.4.22"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
wasmtime = { version = "23.0.1", features = ["runtime", "async"] }
wasmtime-wasi = "23.0.1"
